"""fixed shelter animal relationship

Revision ID: 03aaffa467d3
Revises: 9925dd3aceff
Create Date: 2024-02-23 14:51:33.023670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03aaffa467d3'
down_revision = '9925dd3aceff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('shelter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('shelter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
